"""Moved models to models.py and updated models

Revision ID: 2ba493fca827
Revises: 
Create Date: 2024-11-10 15:34:24.746622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba493fca827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blood_pressure_record')
    op.drop_table('user')
    op.drop_table('glucose_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glucose_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('glucose_level', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('time', sa.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blood_pressure_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('systolic', sa.INTEGER(), nullable=False),
    sa.Column('diastolic', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('time', sa.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
